---
containers:
  - name: gitea
    image: gitea/gitea:1.16.8-rootless
    ports:
      - name: gitea
        containerPort: 3000
        protocol: TCP
    environment:
      GITEA__DEFAULT__RUN_MODE: dev
      GITEA__database__DB_TYPE: sqlite3
      GITEA__database__PATH: /data/gitea/gitea.db
      GITEA__picture__DISABLE_GRAVATAR: "true"
      GITEA__repository__DEFAULT_PRIVATE: "false"
      GITEA__repository__DEFAULT_PUSH_CREATE_PRIVATE: "false"
      GITEA__repository__ENABLE_PUSH_CREATE_ORG: "true"
      GITEA__repository__ENABLE_PUSH_CREATE_USER: "true"
      GITEA__repository__ONLY_ALLOW_PUSH_IF_GITEA_ENVIRONMENT_SET: "false"
      GITEA__security__INSTALL_LOCK: "true"
      GITEA__server__SSH_DOMAIN: http://gitea
      GITEA__service__DISABLE_REGISTRATION: "true"
      GITEA__service__REQUIRE_SIGNIN_VIEW: "false"
      GITEA__webhook__ALLOWED_HOST_LIST: '*'
    volumeMounts:
      - name: gitea-varlib
        mountPath: /var/lib/gitea/
      - name: gitea-data
        mountPath: /data/
      - name: gitea-etc
        mountPath: /etc/gitea
    volumes:
      - name: gitea-data
        emptyDir: {}
      - name: gitea-etc
        emptyDir: {}
      - name: gitea-varlib
        emptyDir: {}
    commands: 
        - gitea admin user create --admin --username gitea --password gitea --email dummy@dummy.com --must-change-password=false
        - >
          curl -X POST -H "accept: application/json" -H "Content-Type: application/json"
          -u 'gitea:gitea' 
          -d '{"username": "student", "full_name": "student", "description": "student"}'
          http://localhost:3000/api/v1/orgs
        - >
          curl -X POST -H "accept: application/json" -H "Content-Type: application/json"
          -u 'gitea:gitea'
          -d '{"clone_addr": "https://github.com/ansible-tmm/aap25-roadshow", "repo_name": "aap25-roadshow-content", "owner": "student", "uid": 2, "private": false}'
          http://localhost:3000/api/v1/repos/migrate
    memory: 2Gi
    services:
      - name: gitea
        ports:
          - port: 3000
            protocol: TCP
            targetPort: 3000
            name: gitea
    routes:
      - name: gitea
        host: gitea
        service: gitea
        targetPort: 3000
        tls: true
        tls_termination: Edge

virtualmachines:
  # Ansible Automation Platform Control Node
  - name: "control"
    image: "aap-2.6-1.1-ceh-20251018"
    memory: "24G"
    cores: 4
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd
    services:
      - name: control
        ports:
          - port: 443
            protocol: TCP
            targetPort: 443
            name: control-https
          - port: 22
            protocol: TCP
            targetPort: 22
            name: control-ssh
    routes:
      - name: control-https
        host: control
        service: control
        targetPort: 443
        tls: true
        tls_termination: reencrypt
        tls_destinationCACertificate: |
          -----BEGIN CERTIFICATE-----
          MIIF/TCCA+WgAwIBAgIUDgOboE2hk+dc9W24VugKGRmc25cwDQYJKoZIhvcNAQEL
          BQAwgYIxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4G
          A1UEBwwHUmFsZWlnaDEQMA4GA1UECgwHUmVkIEhhdDEQMA4GA1UECwwHQW5zaWJs
          ZTEkMCIGA1UEAwwbQW5zaWJsZSBBdXRvbWF0aW9uIFBsYXRmb3JtMB4XDTI1MTAx
          ODEzMDYzOVoXDTM1MTAxNjEzMDYzOVowdjELMAkGA1UEBhMCVVMxFzAVBgNVBAgM
          Dk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMRAwDgYDVQQKDAdSZWQg
          SGF0MRAwDgYDVQQLDAdBbnNpYmxlMRgwFgYDVQQDDA9hYXAuZXhhbXBsZS5vcmcw
          ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCtn/hwNpBmj4G8+3DJdNjw
          5csgPv8scZyb1dV5xqv2F6KGL7QCZVZgsiS4swBFFUhRmkzjq1+hg/fwCghXz3Ml
          qbTekfM1DLuTPozxvHr3/ppOzq9D3xGdzWbUXxn+V/NN6OXCzqGYToRwmkTFaVjv
          6KkXH5jXaR8DqNtchSP8zoLAvmkg2iiDzMm99Y1Pop+AQJwqXXy30NgHjLZjefN7
          iqvqlO2FwELtxb/UbTSD3P0eWp92rst8O01//Mn7UApN8GPQikOUui0qXVdJJaTV
          7rehpda6rBs698a/trQFo/xW3XOV7JZseKXapaod8+nyXhjqhMm7FkGxeYaHpKU5
          HdKJpK277dMnBx+XzOXcCBVcBDKuLgQdisthRJxLR+w8QVaMenLzqHmy1NA4s6JQ
          i2pdO2kQ9d/N51yp7flKvKGZYfPqFdIHF+0qcAOC8cbl1AWWze1CJlHKQ6Bt4yc8
          bJzYy7FzrcJIUht00U6OqhzeK+NccFkdk41ruaaBSqc0t0n07rJj9uGe3ED6gKaE
          zVukCKPCXtitkejfxDxn9WS+rxcdLo2HQldWCXeWBb5p0uuvpUCGPqxADfCSrwac
          0WnGm6OWCbBHvL12evuDuxDRKAfkE73RHWrZLTvYi+qYt8CpE/O75RMvo7O1M1cq
          RwAwYBMMtwZNstFKCdl7eQIDAQABo3YwdDAyBgNVHREEKzApgg9hYXAuZXhhbXBs
          ZS5vcmeHBKwfGYOHEP6AAAAAAAAACP/Y//4mxt0wHQYDVR0OBBYEFDDYAZkj6ved
          L320K/4GhbiGqNasMB8GA1UdIwQYMBaAFCoUqoKpNH1OY8jz0JZqCgCom8xIMA0G
          CSqGSIb3DQEBCwUAA4ICAQArlGJKauj2UbbpVQdOs9a+/B6KSy5P/hNHL/nb+fQf
          e2B0y6umDXDiNunWisn8BFgIojihxmkJ3R1cbAapy8lsVtIZUqapVqi2I6gJaiFa
          KDffvYevgm7Emhy9g9skGz2AGM4RaDvkR+ndFw/DAoYbIWDBk1ofsXbOwepvZGt4
          8o5YHqJtnE4MmRL7tqElANt/z8Gq9JSaGtzpB2BIxYaxlnIgrU9XUXbTUaN7WsAa
          Xc91xgJURYGC7C7UCXK26YRAwPBB/B97nTz7un6c8A/m6yZwCs7gv9/GeZAG86pQ
          S7HQ2fYJD9Kk3V/2pvUestFxoSqFFzwFytP8InvFWrmlUCoq12GbgwmBUfcpEK67
          XICTtYyjcmbGaS2rlvH//wrl5miDIfzJ72xQEKQs+VILOHIC0STPbS9SzrT6RhZL
          3dTgzqXp4mtXJyZJCA7XuDhH+7fBq6b12BsBkQGbdxEPXo5dI2O/ByMa00s9Oyjc
          WMsvDKCtkxrmE+Kmhm7UeSWeyZLgDFKP8RmL0M/fAOq+tMY1PoIxwJNYoazM+R4B
          D8/M42e3R1kcwcqAlwJdWZ5bFghIcJw5POoYKD5OKvx1X51MW5no91l8wC4jzNvd
          mglM9nm2W7N5428xBvo5uHAlNDPUJ06+aieH2owCruvPy95UpmOOL7E1dcGaT1kY
          fw==
          -----END CERTIFICATE-----

  - name: "node01"
    image: "rhel-9.5"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }  
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd

  - name: "node02"
    image: "rhel-8.7"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    services:
      - name: node02-http
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: node02
    routes:
      - name: node02-web
        host: node02
        service: node02-http
        targetPort: 80
        tls: true  ## To resolve https/http Framing
        tls_termination: Edge ## To resolve https/http Framing
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }
      runcmd:
        - sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/" /etc/ssh/sshd_config
        - systemctl reload sshd
        
  - name: "node03"
    image: "rhel-9.5"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    services:
      - name: node03-http
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: node03
    routes:
      - name: node03-web
        host: node03
        service: node03-http
        targetPort: 80
        tls: true
        tls_termination: Edge
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd


  - name: "vscode"
    image: "devtools-ansible"
    memory: "8G"
    cores: 2
    image_size: "20Gi"
    disk_type: "scsi"
    bootloader: "efi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    services:
      - name: vscode-8080
        ports:
          - port: 8080
            protocol: TCP
            targetPort: 8080
            name: vscode
    routes:
      - name: vscode-8080
        host: vscode
        service: vscode-8080
        targetPort: 8080
        tls: true
        tls_termination: Edge
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd